### ISSUE TITLE
ModuleNotFoundError: No module named 'wmi'

### ISSUE THREAD

**Issue by willblev** [nygctech/PySeq2500#15]
I followed the instructions to install pyseq2500 and tested the installation with a few commands (e.g. `pyseq- h`), but when I tried to import pyseq and initialize the HiSeq2500 in python, I got the following error:
``` python
import pyseq
hs = pyseq.HiSeq() 
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "C:\ProgramData\Anaconda3\envs\pyseq…
 line 135, in __init__
   com_ports = get_com_ports('HiSeq2500')
 File "C:\ProgramData\Anaconda3\envs\pyseq…
 line 1076, in get_com_ports
   import wmi
ModuleNotFoundError: No module named 'wmi'
```
This issue was quickly sorted by installing the module with `pip install wmi`, but perhaps it could be added to the pyseq2500 dependencies in a future version.

**Comment by krpandit** [comment]
already updated, need to push new version to pypi
